name: Deploy to JorgasServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest code, Build and Deploy
      run: |
        cd /home/grusite/repo/movies-telegram-bot
        git pull origin main
        echo "Running on $(hostname) as $(whoami)"
        docker compose up --build -d
        docker image prune -f
        docker container prune -f